wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    code_path: code/main.py
    framework: huggingface
    huggingface_version: 4.22.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1672762228.256216
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 14
      - 16
      - 23
      4: 3.9.13
      5: 0.13.3
      6: 4.22.1
      8:
      - 5
auto_resume:
  desc: null
  value: false
batch_size:
  desc: null
  value: 16
best_checkpoint_metric:
  desc: null
  value: loss
checkpoint_prefix:
  desc: null
  value: hi_scratch_mimiciii_seed_42_time_None_
checkpoint_save_path:
  desc: null
  value: /nfs_edlab/ghhur/UniHPF/output/scratch
codebook_negatives:
  desc: null
  value: 0
criterion:
  desc: null
  value: prediction
decoder_dropout:
  desc: null
  value: 0.2
decoder_embed_dim:
  desc: null
  value: 128
decoder_n_heads:
  desc: null
  value: 4
decoder_n_layers:
  desc: null
  value: 4
distributed_rank:
  desc: null
  value: 0
dp:
  desc: null
  value: false
dpe:
  desc: null
  value: true
dropout:
  desc: null
  value: 0.2
dropout_features:
  desc: null
  value: 0.1
dropout_input:
  desc: null
  value: 0.1
edlab_resume:
  desc: null
  value: false
embed_dim:
  desc: null
  value: 128
eval_data:
  desc: null
  value: null
feature_grad_mult:
  desc: null
  value: 0.1
final_dim:
  desc: null
  value: 128
ft_pt_src:
  desc: null
  value: null
ft_pt_task:
  desc: null
  value: null
gen_max_len:
  desc: null
  value: 512
emb_type_model:
  desc: null
  value: descemb
input_path:
  desc: null
  value: /nfs_edlab/ghhur/UniHPF/input
latent_groups:
  desc: null
  value: 2
latent_temp:
  desc: null
  value:
  - 2
  - 0.5
  - 0.999995
latent_vars:
  desc: null
  value: 320
load_checkpoint:
  desc: null
  value: null
log_interval:
  desc: null
  value: 10
log_prefix:
  desc: null
  value: mimiciii_
logit_temp:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.0003
map_layers:
  desc: null
  value: 1
mask_length:
  desc: null
  value: 1
mask_list:
  desc: null
  value:
  - dpe
  - input
  - type
mask_min_space:
  desc: null
  value: 0
mask_other:
  desc: null
  value: 0
mask_prob:
  desc: null
  value: 0.65
mask_selection:
  desc: null
  value: static
max_epoch:
  desc: null
  value: 300
max_seq_len:
  desc: null
  value: 256
max_word_len:
  desc: null
  value: 128
maximize_best_checkpoint_metric:
  desc: null
  value: false
mlm_prob:
  desc: null
  value: 0.15
model:
  desc: null
  value: ehr_model
n_heads:
  desc: null
  value: 4
n_layers:
  desc: null
  value: 2
no_mask_overlap:
  desc: null
  value: false
note_max_seq_len:
  desc: null
  value: 512
note_min_seq_len:
  desc: null
  value: 0
num_negatives:
  desc: null
  value: 25
output_path:
  desc: null
  value: /nfs_edlab/ghhur/UniHPF/output
patience:
  desc: null
  value: 10
perp_weight:
  desc: null
  value: 0.1
port:
  desc: null
  value: '12355'
pos_enc:
  desc: null
  value: true
pred_dim:
  desc: null
  value: 128
pred_model:
  desc: null
  value: eventaggregator
pred_pooling:
  desc: null
  value: mean
pred_src:
  desc: null
  value: mimiciii
pred_tasks:
  desc: null
  value:
  - Task(name='mortality', num_classes=1, property='binary')
  - Task(name='long_term_mortality', num_classes=1, property='binary')
  - Task(name='los_3day', num_classes=1, property='binary')
  - Task(name='los_7day', num_classes=1, property='binary')
  - Task(name='readmission', num_classes=1, property='binary')
  - Task(name='final_acuity', num_classes=8, property='multi-class')
  - Task(name='imminent_discharge', num_classes=8, property='multi-class')
  - Task(name='diagnosis', num_classes=17, property='multi-label')
  - Task(name='creatinine', num_classes=5, property='multi-class')
  - Task(name='bilirubin', num_classes=5, property='multi-class')
  - Task(name='platelets', num_classes=5, property='multi-class')
  - Task(name='wbc', num_classes=3, property='multi-class')
pretrain_src:
  desc: null
  value: mimic3
pretrain_task:
  desc: null
  value: null
pretrained_load:
  desc: null
  value: null
pretrained_path:
  desc: null
  value: null
ratio:
  desc: null
  value: '100'
reg_weight:
  desc: null
  value: 5
resume:
  desc: null
  value: false
resume_path:
  desc: null
  value: null
sample_k:
  desc: null
  value: 5
sample_strategy:
  desc: null
  value: topp
seed:
  desc: null
  value:
  - 42
start_epoch:
  desc: null
  value: 1
structure:
  desc: null
  value: hi
sub_id:
  desc: null
  value: awyaberu
test_batch_size:
  desc: null
  value: 32
text_post_proj:
  desc: null
  value: false
time_embed:
  desc: null
  value: None
train_task:
  desc: null
  value: scratch
type_token:
  desc: null
  value: true
valid_subset:
  desc: null
  value:
  - valid
  - test
wandb:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: hoon9405
wandb_project_name:
  desc: null
  value: hi_prediction
wandb_run_name:
  desc: null
  value: scratch_mimiciii_time_None_seed_42
world_size:
  desc: null
  value: 1
